Mobile version
fherrerao/Capstone-Project pull request #2
Opened 2021-12-23 16:16 UTC by fherrerao

# Hi There
The project has the next features:

- Use of Bootstrap for styling.
- Build Home and About pages.
- The home page should have a link in the menu to the about page.
- The logo in the header links to the home page.
- The section "Featured speakers" was created dynamically in JavaScript.

## Vide Description

Check the video description of the project for general information about it:

https://www.loom.com/share/728eec5d4fc24fa9aa60e960ae6725e6

2021-12-23 18:31 UTC, aliabbani requested changes
Hi @fherrerao, 

Good job so far! I can see real talent here. You really did a great job 🥇 .
However, there are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there! 

 ## Required changes 
_Check the comments under the review._ 

Cheers and Happy coding!👏👏👏 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-23 18:31 UTC, aliabbani commented on README.md
>  - Inspiration
The Acknowledgements section should give appropriate credit to[ Cindy Shin](https://www.behance.net/adagio07) the  [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/). Please make sure to add credit to the original designer.

2021-12-23 18:31 UTC, aliabbani commented on README.md
> +- -Bootstrap
Your readme file looks good👍. Please make it perfect by removing the ( - ) before the Bootstrap word.

2021-12-23 18:31 UTC, aliabbani commented on index.html
> +        </footer>
The footer section in the mobile version should look almost identical to the [original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

Your design:
![image](https://user-images.githubusercontent.com/60292761/147277691-af9274b5-a66f-46f6-99f9-f0b75c01ea2e.png)

The original design : 
![image](https://user-images.githubusercontent.com/60292761/147277733-5a4cec04-2955-4201-b1f6-2b3971d5a497.png)

Please make sure to follow the original design as you can just make it horizontally.

2021-12-23 18:31 UTC, aliabbani commented on index.html
> +        </section>
The partner section in the mobile version should look almost identical to the [original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

Your design:
![image](https://user-images.githubusercontent.com/60292761/147277537-4d145326-18ac-4f24-aff4-861cbd416328.png)

The original design : 
![image](https://user-images.githubusercontent.com/60292761/147277574-c6d3783b-cad0-41b5-8aec-8e2d47c688e5.png)

Please make sure to follow the original design as you can just make it horizontally.

2021-12-23 18:31 UTC, aliabbani commented on index.html
> +                <h2 class="sub-title">CREATIVE COMMONS GLOBAL SUMMIT 2022</h2>
The pages should look almost identical to the original design. Please make sure to add text effect for the h2 as with the [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

2021-12-23 18:31 UTC, aliabbani commented on index.html
> +                </div>
The mobile menu should have a close (X) button that closes the menu. Please add the close (X) button with its functionality.

2021-12-23 18:31 UTC, aliabbani commented on about.html
> +    </footer>
The footer design of the about page should look identical to the footer design of the home page **except** for the colors. Please make sure the padding and margin are the same.

2021-12-24 13:30 UTC, Rustamxon7 approved these changes
## Hi @fherrerao  👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 🎉 🎉 🎉 🎉 

Cheers and Happy coding!👏👏👏

![image](https://user-images.githubusercontent.com/69011963/133591850-fdcb7dd3-dd7a-4274-81e7-0e59434148f7.png)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-12-24 13:58 UTC, merged

2022-02-20 21:17 UTC, fherrerao commented
# Hi @Rustamxon7 
Thanks for your excellent job! 💯